# LOCAL

## Create a new book
###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "description": "The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
  "publishedYear": 1925,
  "genre": "Classic",
  "rating": 4.5
}

## Get all books
###
GET http://localhost:3000/books HTTP/1.1

## Get a book by ID
###
GET http://localhost:3000/books/664d414dc8761c1bf3130a2d HTTP/1.1

## Update a book
###
PUT http://localhost:3000/books/664d414dc8761c1bf3130a2d HTTP/1.1
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "description": "The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
  "publishedYear": 1925,
  "genre": "Classic",
  "rating": 3.2
}

## Delete a book
###
DELETE http://localhost:3000/books/664d414dc8761c1bf3130a2d HTTP/1.1

## Create a new review for a book
###
POST http://localhost:3000/books/664dad98b296d916816427ea/reviews HTTP/1.1
Content-Type: application/json

{
  "reviewer": "John Doe",
  "content": "This book is amazing!",
  "rating": 5
}

## Get all reviews for a book
###
GET http://localhost:3000/reviews/books/664dad98b296d916816427ea/reviews HTTP/1.1

## Update a review for a book
###
PUT http://localhost:3000/reviews/664db38208d9039da5111ccc HTTP/1.1
Content-Type: application/json

{
  "reviewer": "John Doe",
  "content": "This book sucks.",
  "rating": 3
}

## Delete a review for a book
###
DELETE http://localhost:3000/reviews664db38208d9039da5111ccc HTTP/1.1

